version: "3.7"
  
services:
  countries:
      image: countries/java:1.0
      ports:
        - 8080:8080
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
          max_attempts: 5
      environment:
        - SERVICE_PORTS=8080
      networks:
        - jApp
  airport:
      image: airport:1.1
      ports:
        - 8080
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
          max_attempts: 5
      environment:
        - SERVICE_PORTS=8080
      networks:
        - jApp
  new_airport:
    image: airport:1.0.1
    ports:
      - 8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - SERVICE_PORTS=8080
    networks:
      - jApp
  proxy:
      image: dockercloud/haproxy
      depends_on:
          - countries
          - airport
          - new_airport
      environment:
          - BALANCE=leastconn
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      networks:
          - jApp
      ports:
          - 8000:8000
networks:
  jApp:
      driver: overlay
