version: "3.7"
  
services:
  countries:
      image: countires/java:1.0
      ports:
        - 8080:8080
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
          max_attempts: 5
      environment:
        - VIRTUAL_HOST=japp:8080
      networks:
        - jApp
  airport:
      image: airports:1.0.1
      ports:
        - 8070:8080
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
          max_attempts: 5
      environment:
        - VIRTUAL_HOST=japp:8070
      networks:
        - jApp
  new_airport:
    image: airports:1.1
    ports:
      - 8090:8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - VIRTUAL_HOST=japp:8090
    networks:
      - jApp
  proxy:
      image: jwilder/nginx-proxy:alpine
      links:
          - countries
          - airport
          - new_airport
      volumes:
          - ./default.conf:/etc/nginx/conf.d/myconf.conf
          - /var/run/docker.sock:/tmp/docker.sock:ro
      networks:
          - jApp
      ports:
          - 8000:8000
networks:
  jApp:
      driver: overlay
